name: Docker Image CI

env:
  DOCKER_IMAGE: ocm-ingestor
  DOCKER_USER: specialfish9
  DOCKER_USERNAME: specialfish9
  DOCKER_PWD: ${{ secrets.DOCKER_PWD }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: docker login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PWD
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        file: ./ingestor/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE }}:${{ steps.date.outputs.date }}
